In [3]:
#Пункт 2
import numpy as np

# Вариант a: Матрица перехода P
P_a = np.array([[0.19, 0.81], [0.32, 0.68]])

# Вариант b: Матрица перехода P
P_b = np.array([
    [0.26, 0.11, 0.12, 0.15, 0.18, 0.18],
    [0.18, 0.26, 0.11, 0.12, 0.15, 0.18],
    [0.18, 0.18, 0.26, 0.11, 0.12, 0.15],
    [0.15, 0.18, 0.18, 0.26, 0.11, 0.12],
    [0.12, 0.15, 0.18, 0.18, 0.26, 0.11],
    [0.11, 0.12, 0.15, 0.18, 0.18, 0.26]
])


# 2) Находим матрицу перехода за 4 шага
P_a_4 = np.linalg.matrix_power(P_a, 4)
P_b_4 = np.linalg.matrix_power(P_b, 4)

print("Матрица перехода А",P_a_4)
print("Матрица перехода Б", P_b_4)




Матрица перехода А [[0.28339057 0.71660943]
 [0.28310496 0.71689504]]
Матрица перехода Б [[0.16657213 0.16651864 0.16680342 0.16687384 0.16672813 0.16650384]
 [0.16650384 0.16657213 0.16651864 0.16680342 0.16687384 0.16672813]
 [0.16672813 0.16650384 0.16657213 0.16651864 0.16680342 0.16687384]
 [0.16687384 0.16672813 0.16650384 0.16657213 0.16651864 0.16680342]
 [0.16680342 0.16687384 0.16672813 0.16650384 0.16657213 0.16651864]
 [0.16651864 0.16680342 0.16687384 0.16672813 0.16650384 0.16657213]]


In [4]:
# Расчеты пункта 2
import numpy as np

# Исходная матрица P
P = np.array([[0.19, 0.81],
              [0.32, 0.68]])

# Возводим во вторую степень
P_2 = np.linalg.matrix_power(P, 2)

# Выводим результат
print("Матрица P во второй степени:")
print(P_2)

# Возводим в четвертую степень
P_4 = np.linalg.matrix_power(P, 4)

# Выводим результат
print("Матрица P в четвертой степени:")
print(P_4)


Матрица P во второй степени:
[[0.2953 0.7047]
 [0.2784 0.7216]]
Матрица P в четвертой степени:
[[0.28339057 0.71660943]
 [0.28310496 0.71689504]]


In [5]:
#пункт 3
import numpy as np

# Исходная матрица P (вариант А)
P_A = np.array([[0.19, 0.81],
                [0.32, 0.68]])

# Начальные распределения для варианта А
pi_0_A = np.array([1, 0])  # начальное распределение для случая А

# Вычисление распределения вероятностей после 4-го шага для варианта А
pi_4_A = np.dot(np.linalg.matrix_power(P_A.T, 4), pi_0_A)

# Вывод результатов для варианта А
print("Матрица P (вариант А):")
print(P_A)
print("\nРаспределение вероятностей после 4-го шага для случая A:")
print(pi_4_A)

# Новая матрица P (вариант Б)
P_B = np.array([[0.26, 0.11, 0.12, 0.15],
                [0.18, 0.18, 0.18, 0.26],
                [0.11, 0.12, 0.15, 0.18],
                [0.18, 0.18, 0.26, 0.11]])

# Начальные распределения для варианта Б
pi_0_B = np.array([100000, 0, 0, 0])  # начальное распределение для случая Б

# Вычисление распределения вероятностей после 4-го шага для варианта Б
pi_4_B = np.dot(np.linalg.matrix_power(P_B.T, 4), pi_0_B)

# Вывод результатов для варианта Б
print("\nНовая матрица P (вариант Б):")
print(P_B)
print("\nРаспределение вероятностей после 4-го шага для случая B:")
print(pi_4_B)



Матрица P (вариант А):
[[0.19 0.81]
 [0.32 0.68]]

Распределение вероятностей после 4-го шага для случая A:
[0.28339057 0.71660943]

Новая матрица P (вариант Б):
[[0.26 0.11 0.12 0.15]
 [0.18 0.18 0.18 0.26]
 [0.11 0.12 0.15 0.18]
 [0.18 0.18 0.26 0.11]]

Распределение вероятностей после 4-го шага для случая B:
[5356.472 4227.94  5122.1   4982.475]


In [6]:
#Пункт 4
import numpy as np

def solve_stationary_distribution(P):
    # Проверка, что матрица P является квадратной
    if P.shape[0] != P.shape[1]:
        raise ValueError("Матрица P должна быть квадратной")

    # Уравнение для стационарного распределения: p1 P = p1, p2 P = p2
    # p1 + p2 = 1
    A = np.vstack((P.T - np.eye(len(P)), np.ones(len(P))))#1

    # Вектор правой части
    b = np.zeros(len(P) + 1)
    b[-1] = 1

    # Решение системы линейных уравнений
    solution = np.linalg.lstsq(A, b, rcond=None)[0] #2

    # Нормировка, чтобы получить вероятностное распределение
    stationary_distribution = solution / np.sum(solution)#3

    return stationary_distribution

# a) Матрица P для случая A
P_A = np.array([[0.19, 0.81],
                [0.32, 0.68]])

# Решение для случая A
solution_A = solve_stationary_distribution(P_A)
print("Решение для случая A (p1, p2):", solution_A)

# b) Матрица P для случая B
P_B = np.array([[0.26, 0.11, 0.12, 0.15],
                [0.18, 0.18, 0.18, 0.26],
                [0.11, 0.12, 0.15, 0.18],
                [0.18, 0.18, 0.26, 0.11]])

# Решение для случая B
solution_B = solve_stationary_distribution(P_B)
print("Решение для случая B (p1, p2, p3, p4):", solution_B)



Решение для случая A (p1, p2): [0.28318584 0.71681416]
Решение для случая B (p1, p2, p3, p4): [0.25958481 0.23663616 0.24770269 0.25607634]


In [7]:
#Пункт 5
from numpy.random import uniform
import numpy as np

matrixA = np.array([[0.19, 0.81],
                [0.32, 0.68]])

matrixB = np.array([[0.26, 0.11, 0.12, 0.15],
                [0.18, 0.18, 0.18, 0.26],
                [0.11, 0.12, 0.15, 0.18],
                [0.18, 0.18, 0.26, 0.11]])


def predict(matrix):#смоделированное
    steps = 5000 #кол-во шагов в каждой итерации
    count = 5000 #количество генераций 2-3 минуты

    d = {}  # создаем пустой словарь для подсчета количества посещений каждого состояния
    # Инициализация словаря, все состояния начинаются с 0 посещений
    for state in range(len(matrix)):   #цикл for идет по всем состояниям цепи Маркова-равное количеству строк в матрице).
        d[state] = 0#Для каждого состояния state в цикле устанавливается начальное значение в словаре d. В данном случае, значение устанавливается в 0, что предполагает, что изначально ни одно состояние не было посещено

    for _ in range(count):#Это внешний цикл for, который повторяется count раз- обеспечивает повторяемость симуляций,
        cur = 0#Это устанавливает начальное состояние cur в 0 перед каждой новой генерацией цепи Маркова
        for _ in range(steps):#цикл for, который повторяется steps раз. Этот цикл представляет шаги, которые цепь Маркова выполняет в ходе симуляции.
            line = matrix[cur]# переменной line присваивается значение, которое представляет собой текущую строку матрицы matrix для текущего состояния cur. В контексте цепи Маркова, эта строка матрицы представляет собой вероятности перехода из текущего состояния в другие состояния.
            p = uniform(0, 1)# генерируется случайное число p из равномерного распределения на интервале [0, 1].
            sum = 0#переменная будет использоваться для накопления вероятностей при проходе по строке матрицы.
            for i in range(len(line)):# цикла, который проходит по всем элементам текущей строки матрицы line. len(line) возвращает количество элементов в этой строке.
                sum += line[i]#при проходе по элементу line[i], значение этого элемента прибавляется к текущей сумме sum. Это создает кумулятивные вероятности: sum становится суммой вероятностей всех предыдущих элементов и текущего.
                if p < sum:#Если случайное число p, сгенерированное ранее, меньше чем текущая сумма sum, то выполняется следующий блок кода.
                    cur = i#Если условие p < sum истинно, то переменной cur присваивается значение i, которое представляет индекс элемента в строке матрицы. Это значение i будет соответствовать состоянию, в которое следует перейти
                    break# Это обеспечивает выход из цикла, поскольку уже принято решение о следующем состоянии.
        d[cur] += 1 #увеличивается значение в словаре d для текущего состояния cur. То есть, после совершения шага цепи Маркова и определения нового состояния, соответствующий счетчик в словаре увеличивается на 1.
    for state in range(len(matrix)):#Для каждого состояния в цикле
        print(d[state] / count, end=' ')#вычисляется отношение количества посещений (значение в словаре d) к общему числу генераций (count).Ni- количество раз, которое генерация завершалась в состоянии i, а N - общее количество генераций (count).
    print()#, после каждой генерации цепи Маркова выводится строка с эмпирическим распределением посещений для всех состояний.

def solve(matrix):#теоретическое распределение
    tr = []# будет содержать транспонированную матрицу matrix
    for j in range(len(matrix[0])):#цикл, который проходит по индексам столбцов матрицы matrix
        tr.append([])#Для каждого столбца добавляется пустой список в tr. Это создает список списков, который будет представлять собой транспонированную матрицу.
        for i in range(len(matrix)):#цикл проходит по индексам строк матрицы matrix
            tr[j].append(matrix[i][j])# значение из транспонированной матрицы tr в столбце j (созданном на предыдущем шаге) заполняется элементом из оригинальной матрицы matrix. Это осуществляет транспонирование матрицы.
    A = []#пустой список A, который будет содержать строки матрицы.
    for i in range(len(tr)):#цикл, который проходит по индексам строк транспонированной матрицы tr.
        A.append([])#добавляется пустой список в A
        for j in range(len(tr[0])):#цикл проходит по индексам столбцов транспонированной матрицы tr
            if i == j:#проверяется условие, что индекс строки i равен индексу столбца j. Если это условие истинно, значит, мы находимся на главной диагонали матрицы.
                A[i].append(1 - tr[i][j])#в список A[i] добавляется элемент, равный 1 - tr[i][j]. Это выполняется для всех элементов на главной диагонали матрицы, а остальные элементы останутся равными 0.
            else:
                A[i].append(-tr[i][j])#в список A[i] добавляется элемент, равный -tr[i][j]. Это выполняется для элементов, не находящихся на главной диагонали матрицы.
    A.pop()#удаляет последнюю строку из матрицы A. В предыдущем коде, когда выполнялось добавление в A, была добавлена строка, которая состояла из единиц (последняя строка, добавленная в предыдущем блоке кода). Теперь эта строка удаляется.
    A.append([1 for _ in range(len(tr[0]))])#добавляет новую строку в матрицу A, которая состоит из единиц. Длина этой строки равна количеству столбцов в транспонированной матрице tr.
    b = [0 for _ in range(len(tr) - 1)]#создают вектор b, который используется в решении линейной системы. Вектор начинается с нулей и имеет длину на единицу меньше количества строк в транспонированной матрице tr.
    b.append(1)#добавляется значение 1 в конец вектора.
    ans = np.linalg.solve(A, b)# для решения линейной системы уравнений, где A - матрица коэффициентов, b - вектор свободных членов. Результат сохраняется в переменной ans и выводится на экран.
    print(ans)

#solve(matrixA)#выведено теоретическое распределение для цепи Маркова,
#solve(matrixB)#числовым представлением решения линейной системы уравнений, построенной на основе матрицы переходов matrixA.
predict(matrixA)#моделирует цепь Маркова
predict(matrixB)


0.2826 0.7174 
0.2846 0.1766 0.2992 0.2396 


In [10]:
def simulate_discrete_variable(matrix, initial_state, num_steps):
    current_state = initial_state#Устанавливаем начальное состояние в текущее состояние. Это начальное состояние передается в функцию как аргумент initial_state.
    states = [current_state]#Создаем список states, в который мы будем записывать последовательность состояний в процессе моделирования. Начальное состояние добавляется в этот список.

    for _ in range(num_steps):#Запускаем цикл, который повторяется num_steps раз. Этот цикл представляет собой шаги моделирования в течение определенного количества времени.
        line = matrix[current_state]#Получаем текущую строку матрицы переходов, которая представляет вероятности перехода из текущего состояния в другие состояния.
        p = uniform(0, 1)# Генерируем случайное число p из равномерного распределения на интервале [0, 1]. Это число будет использоваться для принятия решения о следующем состоянии.
        cumulative_prob = 0#Инициализируем переменную cumulative_prob, которая будет использоваться для накопления вероятностей при проходе по строке матрицы.

        max_attempts = 100
        for i in range(len(line)):#цикл, который проходит по всем элементам текущей строки матрицы. Для каждого элемента:
            cumulative_prob += line[i]#Накапливаем вероятность текущего перехода.

            if p < cumulative_prob:#Проверяем, достигли ли мы или превысили ли мы случайное число p накопленную вероятность.
                current_state = i# Если условие выполняется, то мы принимаем решение перейти в состояние i.
                states.append(current_state)#Добавляем текущее состояние в список states, представляя тем самым последовательность состояний в процессе моделирования.
                break
            else:
    # Если мы не перешли в новое состояние после max_attempts попыток,
    # принудительно переходим в другое состояние (можно выбрать случайное).
                current_state = np.random.choice(len(matrix[current_state]))

    return states
num_steps = 100
initial_state = 0

simulated_states_A = simulate_discrete_variable(matrixA, initial_state, num_steps)
print("Simulated States for matrixA:", simulated_states_A)

simulated_states_B = simulate_discrete_variable(matrixB, initial_state, num_steps)
print("Simulated States for matrixB:", simulated_states_B)


Simulated States for matrixA: [0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1]
Simulated States for matrixB: [0, 1, 2, 1, 2, 3, 1, 0, 1, 0, 3, 3, 0, 2, 3, 1, 0, 0, 1, 2, 2, 3, 2, 1, 3, 1, 3, 1, 3, 0, 3, 1, 2, 1, 1, 1, 1, 3, 1, 2, 2, 3, 0, 0, 1, 2, 1, 1, 2, 0, 1, 1, 2, 2, 1, 1, 1, 0, 2, 3, 1, 3, 2, 2, 1, 1, 2, 1, 3, 2, 2, 3]



Моделировать переходы из состояние в состояние - это получать число в пределах от номера первого состояния, например 0 или 1, до последнего, соответственно, 5 или 6 в данном примере, а затем брать из матрицы переходов строку, соответствующую полученному числу (эта строка - распределение вероятностей), и подавать на вход алгоритму для моделирования дискретной с.в. (то есть каждый раз дискретная с. в. моделируется по новому распределению вероятностей)



   Получаем текущую строку матрицы переходов, которая представляет вероятности перехода из текущего состояния в другие состояния.
   Генерируем случайное число p из равномерного распределения на интервале
    [0, 1]
     Это число будет использоваться для принятия решения о следующем состоянии.
  Инициализируем переменную , которая будет использоваться для накопления вероятностей при проходе по строке матрицы.
        
 цикл, который проходит по всем элементам текущей строки матрицы. Для каждого элемента:
  Накапливаем вероятность текущего перехода.

  Проверяем, достигли ли мы или превысили ли мы случайное число p накопленную вероятность.

  Если накопленная вероятность становится больше или равна случайному числу p, это означает, что мы достигли или превысили значение, необходимое для принятия решения о переходе в новое состояние.

  Когда условие cumulative_prob >= p выполняется для элемента с индексом i, мы принимаем решение перейти в состояние i.

 то мы принимаем решение перейти в состояние i.

  Добавляем текущее состояние в список states, представляя тем самым последовательность состояний в процессе моделирования.
